[package]
name = "raytracer"
version = "0.1.0"
authors = ["Megan Pycroft <megan.pycroft@gmail.com>"]
edition = "2021"
description = "A ray tracer written in Rust"
license = "MIT"

[dependencies]
anyhow = "1.0.75"
derive_more = "0.99.17"
float-cmp = "0.9.0"

[lints.clippy]
pedantic = "warn"
